#!/bin/bash

# install oh-my-zsh
curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh

# install a zsh theme
mkdir -p ~/.oh-my-zsh/custom/themes/powerlevel9k
curl -o ~/.oh-my-zsh/custom/themes/powerlevel9k/powerlevel9k.zsh-theme https://raw.githubusercontent.com/bhilburn/powerlevel9k/master/powerlevel9k.zsh-theme

# set the zsh theme
sed -i '' 's/^ZSH_THEME=".*"/ZSH_THEME="powerlevel9k\/powerlevel9k"/g' ~/.zshrc

# zsh theme variable
echo "export DEFAULT_USER=steve" >> ~/.zshrc

# download Input font from http://input.fontbureau.com/download/
