#!/bin/bash

# install oh-my-zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

# install a zsh theme
git clone https://github.com/bhilburn/powerlevel9k.git ~/.oh-my-zsh/custom/themes/powerlevel9k

# set the zsh theme
sed -i '' 's/^ZSH_THEME=".*"/ZSH_THEME="powerlevel9k\/powerlevel9k"/g' ~/.zshrc

# set up theme variables
cat >> ~/.zshrc << EOM
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir virtualenv vcs)

export DEFAULT_USER=steve
EOM

# download Input font from http://input.fontbureau.com/download/
